name: AI Label PR Based on Description

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get PR details
        id: get_pr
        run: |
          PR_INFO=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}")

          PR_TITLE=$(echo "$PR_INFO" | jq -r '.title')
          PR_BODY=$(echo "$PR_INFO" | jq -r '.body' | sed -E 's/<details>.*<\/details>//g' | tr -d '\r' | tr '\n' ' ')
          
          # Trim PR-body hvis den er for lang
          PR_BODY_SHORT=$(echo "$PR_BODY" | cut -c1-500)

          # Escape strings til korrekt JSON-format
          echo "PR_TITLE=$(echo "$PR_TITLE" | jq -Rs .)" >> $GITHUB_ENV
          echo "PR_BODY_SHORT=$(echo "$PR_BODY_SHORT" | jq -Rs .)" >> $GITHUB_ENV

      - name: Get available labels
        id: get_labels
        run: |
          LABELS=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/labels" | jq -r '.[].name')

          AVAILABLE_LABELS=$(echo "$LABELS" | jq -R -s -c 'split("\n")[:-1]')
          echo "AVAILABLE_LABELS=$AVAILABLE_LABELS" >> $GITHUB_ENV

      - name: Call OpenAI API for Label Prediction
        id: openai_request
        run: |
          # Byg JSON payload korrekt med jq for at sikre gyldigt format
          PAYLOAD=$(jq -n \
              --arg pr_title "$PR_TITLE" \
              --arg pr_body_short "$PR_BODY_SHORT" \
              --arg available_labels "$AVAILABLE_LABELS" \
              '{
                  model: "gpt-4-turbo",
                  messages: [
                      {
                          role: "system",
                          content: "You are a GitHub automation bot. Based on the given pull request title and description, return a JSON array with the most relevant labels from the available labels. Only return the JSON array."
                      },
                      {
                          role: "user",
                          content: ("Pull Request Title: \($pr_title)\nPull Request Description: \($pr_body_short)\nAvailable Labels: \($available_labels)\n\nReturn a JSON array of the most relevant labels.")
                      }
                  ],
                  temperature: 0.3,
                  max_tokens: 50
              }')

          echo "Sending the following JSON payload to OpenAI API:"
          echo "$PAYLOAD"

          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD")

          echo "OpenAI Response: $RESPONSE"

          # Håndter fejl, hvis OpenAI ikke returnerer noget brugbart
          if [ -z "$RESPONSE" ] || echo "$RESPONSE" | jq -e '.error' >/dev/null; then
            echo "❌ OpenAI API call failed. Exiting."
            exit 1
          fi

          # Hent labels fra OpenAI's svar
          LABELS=$(echo "$RESPONSE" | jq -r '.choices[0].message.content' | jq -c '.' 2>/dev/null || echo "[]")

          if [ "$LABELS" == "[]" ] || [ -z "$LABELS" ]; then
            echo "⚠️ No relevant labels found. Exiting."
            exit 0
          fi

          echo "LABELS=$LABELS" >> $GITHUB_ENV

      - name: Apply Labels
        run: |
          curl -s -X POST -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "{\"labels\": $LABELS}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels"

      - name: Comment on Pull Request
        run: |
          COMMENT_BODY=$(jq -n --arg labels "$LABELS" \
            '{
                body: ("The following labels have been added based on the pull request title and description: " + $labels)
            }')

          curl -s -X POST -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "$COMMENT_BODY" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
