name: Release Workflow

on:
  release:
    types: [published]

permissions:
  contents: write  # Påkrævet for at committe ændringer

jobs:
  release_process:
    name: Handle Release
    runs-on: ubuntu-latest
    steps:

      ## Step 1: Hent versionsnummer fra tag
      - name: Get Release Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      ## Step 2: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      ## Step 3: Opdater manifest.json
      - name: Update manifest.json
        run: |
          FILE="custom_components/braendstofpriser/manifest.json"
          jq --arg v "$VERSION" '.version = $v' "$FILE" > temp.json && mv temp.json "$FILE"

      ## Step 4: Commit ændringen direkte til main
      - name: Commit and Push manifest.json update
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add custom_components/braendstofpriser/manifest.json
          git commit -m "Update manifest.json to version $VERSION"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      ## Step 5: Zip indholdet af mappen
      - name: Create zip file
        run: |
          cd custom_components/braendstofpriser
          zip -r ../../braendstofpriser.zip ./
          cd ../..

      ## Step 6: Upload zip-filen til releasen
      - name: Upload Zip to Release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}
          file: braendstofpriser.zip
          asset_name: braendstofpriser.zip
          tag: ${{ github.ref }}
          overwrite: true
